spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bsm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 172.29.96.1
      port: 6379
      password: 123456
      database: 0

# MyBatis ??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

dubbo:
  application:
    name: dubbo-demo-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://172.29.96.1:8848?timeout=30000  # 30秒超时
    #    address: zookeeper://127.0.0.1:2181?timeout=30000  # 30秒超时
    parameters:
      session.timeout: 30000