## 应用名称
#dubbo:
#  application:
#    name: user-server
#  protocol: # 指定通信规则
#    name: dubbo # 通信协议
#    port: -1 # dubbo协议端口，以供消费者访问，-1即为随机端口
#  registry: # 注册中心
#    id: zk-registry
#    address: zookeeper://127.0.0.1:2181
#
## 应用服务 WEB 访问端口
server:
  port: 8090

dubbo:
  application:
    name: bsm-battery-waring
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://172.29.96.1:8848?timeout=30000  # 30秒超时
    #    address: zookeeper://127.0.0.1:2181?timeout=30000  # 30秒超时
    parameters:
      session.timeout: 30000

rocketmq:
  name-server:
    localhost:9876
  producer:
    group: BsmBatteryInfoGroup
  consumer:
    group: BsmBatteryWaringGroup